# ===================================================================
#                        ALACRITTY CONFIGURATION
# ===================================================================
# Beautiful terminal configuration with Nord theme and glass effect
# Author: cxrlos
# Theme: Nord
# Font: Hack 12pt
# Features: Transparency, smooth scrolling, optimized performance
# ===================================================================

# ===================================================================
# WINDOW CONFIGURATION
# ===================================================================
[window]
# Window dimensions (changes require restart)
dimensions = { columns = 120, lines = 30 }

# Window padding (changes require restart)
padding = { x = 12, y = 12 }

# Spread additional padding evenly around the terminal content
dynamic_padding = true

# Background opacity
# Window opacity as a floating point number from 0.0 to 1.0
# The value 0.0 is completely transparent and 1.0 is opaque
opacity = 0.95

# Window decorations
# Values for decorations:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
decorations = "full"

# Startup Mode (changes require restart)
# Values for startup_mode:
#   - Windowed
#   - Maximized
#   - Fullscreen
startup_mode = "Windowed"

# Window title
title = "Terminal"

# Allow terminal applications to change Alacritty's window title
dynamic_title = true

# ===================================================================
# SCROLLING CONFIGURATION
# ===================================================================
[scrolling]
# Maximum number of lines in the scrollback buffer
# Specifying '0' will disable scrolling
history = 10000

# Scrolling distance multiplier
multiplier = 3

# ===================================================================
# FONT CONFIGURATION
# ===================================================================
[font]
# Normal (roman) font face
# Note: Alacritty will try system fallback if specified font is not available
normal = { family = "Hack Nerd Font Mono, Hack Nerd Font, Hack, JetBrains Mono, monospace", style = "Regular" }

# Bold font face
bold = { family = "Hack Nerd Font Mono, Hack Nerd Font, Hack, JetBrains Mono, monospace", style = "Bold" }

# Italic font face
italic = { family = "Hack Nerd Font Mono, Hack Nerd Font, Hack, JetBrains Mono, monospace", style = "Italic" }

# Bold italic font face
bold_italic = { family = "Hack Nerd Font Mono, Hack Nerd Font, Hack, JetBrains Mono, monospace", style = "Bold Italic" }

# Point size
size = 12.0

# Offset is the extra space around each character. `offset.y` can be thought
# of as modifying the line spacing, and `offset.x` as modifying the letter
# spacing.
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells with
# the default being at the bottom. Increasing `x` moves the glyph to the
# right, increasing `y` moves the glyph upward.
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters
builtin_box_drawing = true

# ===================================================================
# NORD COLOR SCHEME
# ===================================================================
[colors]
# Default colors
primary = { background = "#2e3440", foreground = "#d8dee9", dim_foreground = "#a5abb6" }

# Cursor colors
cursor = { text = "#2e3440", cursor = "#d8dee9" }

# Vi mode cursor colors
vi_mode_cursor = { text = "#2e3440", cursor = "#d8dee9" }

# Selection colors
selection = { text = "CellForeground", background = "#4c566a" }

# Search colors
search = { matches = { foreground = "#2e3440", background = "#88c0d0" }, focused_match = { foreground = "#2e3440", background = "#5e81ac" } }

# Normal colors
normal = { black = "#3b4252", red = "#bf616a", green = "#a3be8c", yellow = "#ebcb8b", blue = "#81a1c1", magenta = "#b48ead", cyan = "#88c0d0", white = "#e5e9f0" }

# Bright colors
bright = { black = "#4c566a", red = "#bf616a", green = "#a3be8c", yellow = "#ebcb8b", blue = "#81a1c1", magenta = "#b48ead", cyan = "#8fbcbb", white = "#eceff4" }

# Dim colors
dim = { black = "#373e4d", red = "#94545d", green = "#809575", yellow = "#b29e75", blue = "#68809a", magenta = "#8c738c", cyan = "#6d96a5", white = "#aeb3bb" }

# ===================================================================
# CURSOR CONFIGURATION
# ===================================================================
[cursor]
# Cursor style
style = { shape = "Block", blinking = "On" }

# Vi mode cursor style
vi_mode_style = { shape = "Beam", blinking = "On" }

# Cursor blinking interval in milliseconds
blink_interval = 750

# If this is true, the cursor will be rendered as a hollow box when the
# window is not focused
unfocused_hollow = true

# Thickness of the cursor relative to the cell width as floating point number
# from 0.0 to 1.0
thickness = 0.15

# ===================================================================
# MOUSE CONFIGURATION
# ===================================================================
[mouse]
# If this is true, the cursor is temporarily hidden when typing
hide_when_typing = true

# ===================================================================
# DEBUG CONFIGURATION
# ===================================================================
[debug]
# Display the time it takes to redraw each frame
render_timer = false

# Log level
# Values for log_level:
#   - Off
#   - Error
#   - Warn
#   - Info
#   - Debug
#   - Trace
log_level = "Warn"

# Print all received window events
print_events = false
