# ===================================================================
#                        STARSHIP CONFIGURATION
# ===================================================================
# Starship prompt configuration with Nord color theme
# Author: cxrlos
# Features: Clean, fast, context-aware, Nord-themed
# ===================================================================

# ===================================================================
# NORD COLOR PALETTE
# ===================================================================

# Nord color definitions (for reference)
# nord_cyan = "#88C0D0"
# nord_blue = "#81A1C1"
# nord_green = "#A3BE8C"
# nord_red = "#BF616A"
# nord_orange = "#D08770"
# nord_yellow = "#EBCB8B"
# nord_purple = "#B48EAD"
# nord_snow = "#ECEFF4"

# ===================================================================
# PROMPT FORMAT
# ===================================================================

# Main prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$python\
$nodejs\
$rust\
$golang\
$docker_context\
$package\
$cmd_duration\
$jobs\
$line_break\
$character"""

# -------------------------------------------------------------------
# GLOBAL PERFORMANCE TUNING
# -------------------------------------------------------------------
# Reduce filesystem scan time and limit long-running external commands
scan_timeout = 15      # ms to look for files before bailing out
command_timeout = 1000 # ms allowed for git/other commands (warns when exceeded)

# ===================================================================
# MODULE CONFIGURATIONS
# ===================================================================

# Username module
[username]
style_user = "bold #88C0D0"  # Nord cyan
style_root = "bold #BF616A"  # Nord red
format = "[$user]($style) "
disabled = false
show_always = false

# Hostname module
[hostname]
ssh_only = true
format = "on [$hostname](bold #81A1C1) "  # Nord blue
disabled = false

# Directory module
[directory]
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "bold #88C0D0"  # Nord cyan
read_only = ""
read_only_style = "bold #BF616A"  # Nord red

# Git module
[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold #A3BE8C"  # Nord green
symbol = " "  # Git branch icon

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold #BF616A"  # Nord red
# Refreshed, powerlevel-style glyphs for clarity
conflicted = ""  # branch conflict icon
ahead      = "⇡${count}"
behind     = "⇣${count}"
untracked  = "?"
stashed    = ""
modified   = "✚"
staged     = "●"
renamed    = "➜"
deleted    = "✖"
ignore_submodules = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold #88C0D0"  # Nord cyan

# Python module (virtual environment)
[python]
format = 'via [$symbol$virtualenv]($style) '
style = "bold #EBCB8B"  # Nord yellow
symbol = " "
detect_extensions = []
detect_files = []
detect_folders = []
python_binary = ["python", "python3", "python2"]
version_format = "v${raw}"

# ===================================================================
# CLOUD MODULES (ONLY AT ROOT)
# ===================================================================

# Google Cloud module
[gcloud]
format = 'on [$symbol$project(@$domain)]($style) '
style = "bold #88C0D0"  # Nord cyan
symbol = "☁️  "
disabled = true

# ===================================================================
# UTILITY MODULES
# ===================================================================

# Command duration
[cmd_duration]
format = "took [$duration](bold #EBCB8B) "  # Nord yellow
min_time = 2_000
show_milliseconds = false

# -------------------------------------------------------------------
# BACKGROUND/JOB INDICATOR (Suspended processes)
# -------------------------------------------------------------------
[jobs]
symbol = "✦"
style  = "bold #EBCB8B"
format = "[$symbol]($style) "

# Character module
[character]
success_symbol = "[](bold #A3BE8C)"  # Nord green
error_symbol = "[](bold #BF616A)"    # Nord red
vicmd_symbol = "[](bold #88C0D0)"    # Nord cyan

# ===================================================================
# DEVELOPMENT ENVIRONMENT MODULES
# ===================================================================

# Node.js module
[nodejs]
format = "via [$symbol($version )]($style)"
style = "bold #A3BE8C"  # Nord green
symbol = "󰎙 "
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx", "jsx"]
detect_files = ["package.json", ".nvmrc"]
detect_folders = ["node_modules"]

# Rust module
[rust]
format = "via [$symbol($version )]($style)"
style = "bold #D08770"  # Nord orange
symbol = " "
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]

# Go module
[golang]
format = "via [$symbol($version )]($style)"
style = "bold #88C0D0"  # Nord cyan
symbol = " "
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum", "glide.yaml", "Gopkg.yml", "Gopkg.lock", ".go-version"]
detect_folders = ["Godeps"]

# Docker module
[docker_context]
format = "via [$symbol$context]($style) "
style = "bold #81A1C1"  # Nord blue
symbol = " "
only_with_files = true
detect_extensions = []
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

# Package module
[package]
format = "is [$symbol$version]($style) "
style = "bold #EBCB8B"  # Nord yellow
symbol = "󰏗 "
display_private = false
